name: YouTube Live Stream Debug

on:
  workflow_dispatch:  # Manual trigger

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg xvfb nodejs npm

    - name: Install Node Modules
      run: npm install puppeteer

    - name: Start Virtual Display
      run: |
        # Start Xvfb on display :99 with resolution 1280x720 and 24-bit color depth
        Xvfb :99 -screen 0 1280x720x24 &
        # Set the display environment variable for subsequent steps
        export DISPLAY=:99
        # Give Xvfb a moment to start
        sleep 5

    - name: Launch Webpage with Puppeteer
      run: |
        # Launch our Puppeteer script in the background so it keeps the webpage open
        node stream.js &
        # Wait a few seconds to let the page load
        sleep 10

    - name: Capture Screenshot for Debug
      run: |
        # Capture one frame from the virtual display to verify it's rendering the webpage
        ffmpeg -f x11grab -video_size 1280x720 -i :99.0 -vframes 1 screenshot.png
      env:
        DISPLAY: :99

    - name: Upload Screenshot Artifact
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: screenshot.png

    - name: Start YouTube Stream
      run: |
        # Stream the virtual display to YouTube using FFmpeg with zerolatency tuning
        ffmpeg -f x11grab -video_size 1280x720 -r 30 -i :99.0 \
          -c:v libx264 -preset veryfast -tune zerolatency \
          -b:v 1500k -maxrate 1500k -bufsize 3000k \
          -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.YOUTUBE_STREAM_KEY }}"
      env:
        DISPLAY: :99
